name: 'Bump major version'
on:
  push:
  workflow_dispatch:
description: 'Bump major version of the application'
jobs:
  bump_major_version:
    - name: Get next version
      uses: reecetech/version-increment@2024.4.3
      id: version
      with:
        scheme: semver
        increment: patch

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: "example/application:${{ steps.version.outputs.version }}"
        context: .