[bumpver]
current_version = "v0.0"
version_pattern = "vMAJOR.MINOR"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"README.md" = [
    "current version is {current_version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
