name: 'Commit bump version 001'
on:
  push:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Tick box if you want to bump the major version +1'
        required: true
        type: boolean
jobs:
  bump_major_version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Bump version'
        uses: gabeduke/bumpver-action@v1.0.14
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}