name: 'Bump major version'
on:
  push:
  workflow_dispatch:
jobs:
  bump_major_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: harvidsen/bumpver-action
        with:
          args: --major --dry
