name: 'Bump major version'
on:
  push:
  workflow_dispatch:
jobs:
  bump_major_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get and cache dependencies
        uses: ./actions/cached-deps
        id: cached-deps
        with:
          caching: true

      - name: Bump major version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: semver
          increment: major
