name: 'Bump major version'
on:
  push:
  workflow_dispatch:
jobs:
  git_config:
    runs-on: ubuntu-latest
    steps:
      - name: run git commands
        run: |
          git config --global --add safe.directory /github/workspace
  bump_major_version:
    needs: git_config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run git commands
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Bump version and push tag
        uses: darioblanco/bump-semver@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          defaultBump: major
          prefix: mygroup/
