name: 'Bump major version'
on:
  push:
  workflow_dispatch:
jobs:
  bump_major_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          use_api: true
          scheme: semver
          increment: major