name: Cocogitto major bump
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump'
        required: true
        default: 'major'
        type: choice
        options: 
          - major
          - minor
          - patch
jobs:
  bump-version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version
        run: |
          cog-bump --major --pre "beta.1"
