name: 'Commit and bump'
on: workflow_dispatch
jobs:
  commit_and_bump:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Add and commit'
        uses: EndBug/add-and-commit@v9
        with:
          commit: --allow-empty
          message: '#major'
          push: false
          tag: true
          tag_push: true
