name: Get latest tag
on: workflow_dispatch
jobs:
  get_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          git describe --tags --abbrev=0 > ./versioning-rules/version.json
      - name: Set output
        run: echo "latest_tag=$(cat $GITHUB_ENV/LATEST_TAG)" >> $GITHUB_ENV
