name: Bump version via manual trigger
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump'
        required: true
        default: 'minor'
        type: choice
        options: 
          - major
          - minor
          - patch
jobs:
  bump-version:
      permissions:
          pull-requests: write
          actions: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install dependencies
          run: npm install
        - name: Bump Version
          id: update_version
          run: |
            echo "version=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version)" >> $GITHUB_OUTPUT
        - name: Create pull request
          id: create_pr
          uses: peter-evans/create-pull-request@v5
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: release/${{ steps.update_version.outputs.version }}
            title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
            body: "This pull request contains the updated package.json with the new release version"
            base: main
