name: 'Bump major version'
on: 
  workflow_dispatch:
    inputs:
      Select a job to run:
        description: 'Select a job to run'
        required: true
        type: choice
        options:
          - major-bump
          - major-bump-and-tag
          - major-bump-and-tag-beta
          - major-bump-and-tag-release-candidate
jobs:
  major-bump:
    if: github.event.inputs['Select a job to run'] == 'major-bump'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: clean version file
        run: |
          sed -i 's/-beta//' ./versioning-rules/version.json
          sed -i 's/-rc//' ./versioning-rules/version.json
      - name: Bump Major Version
        uses: michmich112/version-bumper@master
        with:
          options-file: './versioning-rules/major-bumps/bump_only_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  major-bump-and-tag:
    if: github.event.inputs['Select a job to run'] == 'major-bump-and-tag'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          git describe --tags --abbrev=0 > ./versioning-rules/version.json
      - name: print tag
        run: |
          cat ./versioning-rules/version.json
      - name: update version file
        run: |
          sed 's/^/{ "version": "/' ./versioning-rules/version.json
          sed 's/$/" } /' ./versioning-rules/version.json
      - name: print tag
        run: |
            cat ./versioning-rules/version.json
      - name: clean version file
        run: |
          sed -i 's/-beta//' ./versioning-rules/version.json
          sed -i 's/-rc//' ./versioning-rules/version.json
      - name: Bump Major Version and Tag
        uses: michmich112/version-bumper@master
        with:
          options-file: './versioning-rules/major-bumps/bump_and_tag_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  major-bump-and-tag-beta:
    if: github.event.inputs['Select a job to run'] == 'major-bump-and-tag-beta'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: clean version file
        run: |
          sed -i 's/-beta//' ./versioning-rules/version.json
          sed -i 's/-rc//' ./versioning-rules/version.json
      - name: Bump Major Version and Tag Beta
        uses: michmich112/version-bumper@master
        with:
          options-file: './versioning-rules/major-bumps/beta_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  major-bump-and-tag-release-candidate:
    if: github.event.inputs['Select a job to run'] == 'major-bump-and-tag-release-candidate'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: clean version file
        run: |
          sed -i 's/-beta//' ./versioning-rules/version.json
          sed -i 's/-rc//' ./versioning-rules/version.json
      - name: Bump Major Version and Tag Release Candidate
        uses: michmich112/version-bumper@master
        with:
          options-file: './versioning-rules/major-bumps/release_candidate_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
