name: 'Bump major version'
on: 
  workflow_dispatch:
    inputs:
      Select a job to run:
        description: 'Select a job to run'
        required: true
        type: choice
        options:
          - bump-major
          - bump-and-tag-major
jobs:
  major-bump:
    if: github.event.inputs['Select a job to run'] == 'bump-major'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './bump_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  major-bump-and-tag:
    if: github.event.inputs['Select a job to run'] == 'bump-and-tag-major'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './bump_and_tag_options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}