name: 'get tag version'
on: workflow_dispatch
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: './options.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}